[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.3"
rand_chacha = "0.10.0"
rayon = "1.12.0"
xxhash-rust.workspace = true
anyhow.workspace = true
rand_distr = "0.6.0"

[build-dependencies]
cc = "1.4.7"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "generate"
harness = false
