use randomart_core::{grammar::generate_tree_parallel, node::Node};
use xxhash_rust::xxh3::xxh3_64;
use std::fmt::Write;

fn emit_node(out: &mut String, node: &Node) {
    match node {
        Node::X => out.push_str("x"),
        Node::Y => out.push_str("y"),
        Node::Number(v) => write!(out, "({}_f32)", v).unwrap(),

        Node::Add(a, b) => {
            out.push('(');
            emit_node(out, a);
            out.push_str(" + ");
            emit_node(out, b);
            out.push_str(") / 2.0_f32");
        }
        Node::Mult(a, b) => {
            out.push('(');
            emit_node(out, a);
            out.push_str(" * ");
            emit_node(out, b);
            out.push(')');
        }
        Node::Div(a, b) => {
            out.push_str("{ let _d = ");
            emit_node(out, b);
            out.push_str("; if _d.abs() > 1e-6_f32 { (");
            emit_node(out, a);
            out.push_str(") / _d } else { 0.0_f32 } }");
        }
        Node::Sin(inner) => {
            out.push('(');
            emit_node(out, inner);
            out.push_str(").sin()");
        }
        Node::Cos(inner) => {
            out.push('(');
            emit_node(out, inner);
            out.push_str(").cos()");
        }
        Node::Exp(inner) => {
            out.push('(');
            emit_node(out, inner);
            out.push_str(").exp()");
        }
        Node::Sqrt(inner) => {
            out.push_str("(");
            emit_node(out, inner);
            out.push_str(").max(0.0_f32).sqrt()");
        }
        Node::MixUnbounded(a, b, c, d) => {
            out.push_str("{ let _a = ");
            emit_node(out, a);
            out.push_str("; let _b = ");
            emit_node(out, b);
            out.push_str("; let _c = ");
            emit_node(out, c);
            out.push_str("; let _d = ");
            emit_node(out, d);
            out.push_str("; (_a * _c + _b * _d) / (_a + _b + 1e-6_f32) }");
        }

        Node::Triple(_, _, _) => panic!("Triple should not appear in scalar emit"),
        Node::Random => panic!("Random must be resolved before emit"),
        Node::Rule(_) => panic!("Rule must be expanded before emit"),
    }
}

fn emit_channel_fn(name: &str, node: &Node) -> String {
    let mut body = String::new();
    emit_node(&mut body, node);
    format!("#[inline(always)]\npub fn {name}(x: f32, y: f32) -> f32 {{\n    {body}\n}}\n")
}

fn main() {
    let seed_str = std::env::var("RANDOMART_SEED").unwrap_or_else(|_| "default".to_string());
    let depth: u32 = std::env::var("RANDOMART_DEPTH")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(8);

    println!("cargo:rerun-if-env-changed=RANDOMART_SEED");
    println!("cargo:rerun-if-env-changed=RANDOMART_DEPTH");

    let seed = xxh3_64(seed_str.as_bytes());
    let mut node = generate_tree_parallel(seed, depth)
        .expect("failed to generate tree");
    node.simplify_triple();

    let (r, g, b) = match &*node {
        Node::Triple(r, g, b) => (r.as_ref(), g.as_ref(), b.as_ref()),
        _ => panic!("expected Triple at root"),
    };

    let mut src = String::new();
    src.push_str("// AUTO-GENERATED by build.rs — do not edit\n\n");
    src.push_str(&emit_channel_fn("r", r));
    src.push('\n');
    src.push_str(&emit_channel_fn("g", g));
    src.push('\n');
    src.push_str(&emit_channel_fn("b", b));

    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(format!("{out_dir}/generated.rs"), src).unwrap();
}
